publish:
  docker:
    registry: registry.192.168.12.212.xip.io:5000
    repo: oas/packer-buildpack
    tag:
    - latest
    - $$BRANCH-$$COMMIT-$$BUILD_NUMBER
    file: Dockerfile
    insecure: true
