publish:
  docker:
    registry: 192.168.12.212:5000
    repo: oas/packer-buildpack
    tag:
    - latest
    - $$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER
    file: Dockerfile
    insecure: true
    load: drone/docker/image.tar
    save:
      destination: drone/docker/image.tar
      tag: latest

cache:
  mount:
  - drone/docker/image.tar

notify:
  webhook:
    debug: true
    urls:
    - "https://api.telegram.org/bot$$TELEGRAM_BOT_KEY/sendMessage"
    content_type: application/json
    template: >
      {
        "chat_id": "-130629599",
        "text": "{{repo.full_name}} $${BRANCH} $${COMMIT:0:7} $${BUILD_NUMBER} {{build.status}}"
      }
