publish:
  docker:
    registry: 192.168.12.212:5000
    repo: plataforma/packer-buildpack
    tag:
    - latest
    - $${BRANCH=SNAPSHOT}-$${COMMIT:0:7=SNAPSHOT}-$${BUILD_NUMBER=SNAPSHOT}
    file: Dockerfile
    insecure: true
    load: drone/docker/image.tar
    save:
      destination: drone/docker/image.tar
      tag: latest

cache:
  mount:
  - drone/docker/image.tar

notify:
  webhook:
    urls:
    - "https://api.telegram.org/bot$$TELEGRAM_BOT_KEY/sendMessage"
    content_type: application/json
    template: >
      {
        "chat_id": "-130629599",
        "parse_mode": "Markdown",
        "text": "[{{uppercase build.status}}]({{build.link_url}}) {{repo.full_name}}:{{build.branch}}-{{truncate build.commit 7}}-{{build.number}} {{build.author}} authored \"{{truncate build.message 25}}\"... took {{duration build.started_at build.finished_at}}"
      }
