publish:
  docker:
    registry: ci.192.168.12.212.xip.io:5000
    repo: oas/packer-buildpack
    tag:
    - latest
    - $$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER
    file: Dockerfile
    insecure: true
    load: drone/docker/image.tar
    save:
      destination: drone/docker/image.tar
      tag: latest

cache:
  mount:
  - drone/docker/image.tar

notify:
  webhook:
    urls:
    - "https://api.telegram.org/bot$$TELEGRAM_BOT_KEY/sendMessage"
    content_type: application/json
    template: >
      {
        "chat_id": "-130629599",
        "text": "{{uppercase build.status}} [{{repo.full_name}}:{{build.branch}}:{{build.commit}}:{{build.number}}] {{build.author}} authored \"{{build.message}}\""
      }
