publish:
  docker:
    registry: 10.20.0.126:5000
    repo: plataforma/packer-buildpack
    tag:
      - latest
      - $$BRANCH-$${COMMIT:0:7}-$$BUILD_NUMBER
    file: Dockerfile
    insecure: true
    storage_driver: overlay

cache:
  mount:
    - /drone/docker
